name: Bump Verison

on:
    push:
        branches:
            - main

jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./
              with:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
