name: Bump Verison

on:
    push:
        branches:
            - main

jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Update Hash
              run: ./
            - name: Commit files
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git commit -m "Bump Hash" -a
                  git push
              with:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
